<a href="https://colab.research.google.com/github/Yongyong-2/Quantum-Computing-Practice/blob/main/DAY00/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

zero = np.array([[1],
                [0]])

X = np.array([[0,1],
             [1,0]])

print(X @ zero)

[[0]
 [1]]


In [6]:

zero = np.array([[1],
                 [0]])

one = np.array([[0],
                [1]])

plus = (1/np.sqrt(2)) * np.array([[1],
                                  [1]])

print(zero)
print(one)
print(plus)

[[1]
 [0]]
[[0]
 [1]]
[[0.70710678]
 [0.70710678]]


In [8]:
wrong = np.array([[1],
                  [1]])

print(np.linalg.norm(wrong)) # L2 norm 반환 및 출력

1.4142135623730951
